from enum import Enum, auto
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict

class SignalType(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"

class Signal(BaseModel):
    """
    Represents a trading signal generated by a strategy.
    """
    model_config = ConfigDict(use_enum_values=True)

    symbol: str
    timestamp: datetime
    signal_type: SignalType
    entry_price: float
    stop_loss: float
    take_profit: float
    rationale: str
    metadata: dict = Field(default_factory=dict)
    
    @property
    def direction(self) -> str:
        """Backwards compatibility for 'direction' key accessing raw string."""
        if isinstance(self.signal_type, str):
            return self.signal_type
        return self.signal_type.value
